server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_with_spring
    username: root
    password: Kelowna
  jpa:
    hibernate:
      ddl-auto: none

    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: true
logging:
  level:
    root: WARN
    com.EACH: DEBUG
    
cors: 
 originPatterns: http://localhost:8080,http://localhost:3000, https://github.com/Leaolu/rest-with-spring-boot-and-java-erudio
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
   use-root-path: true
 
    
