CREATE TABLE IF NOT EXISTS `books` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(255),
  `launch_date` DATETIME(6) NOT NULL,
  `price` DECIMAL(65,2) NOT NULL,
  `title` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;